### ISSUE TITLE
Pre-trained weights unavailable

### ISSUE THREAD

**Issue by michelleespranita** [SekeunKim/EchoFM#4]
Hi! Thank you for your work! :) I would like to download the pre-trained weights from the Google Drive link you shared, but the folder is currently empty.

Can you please upload the pre-trained weights? Thank you so much!

**Comment by SekeunKim** [comment]
Thanks for asking me about this issue. It has been resolved.

**Comment by keko233** [comment]
Hi! I noticed that this issue was previously marked as resolved, but I’m still unable to find the pre-trained weights in the Google Drive folder (it appears empty). Could you kindly double-check or reupload the files?

Thank you !
